name: Build and Release LaTeX AGBs

on:
  push:
    tags:
      - 'v*'         # Trigger nur bei Tags wie v1.0.0, v2.1 etc.
  workflow_dispatch: # Optional: manueller Trigger über GitHub UI

permissions:
  contents: write

jobs:
  build_latex:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        file: [agb_privat, agb_geschaeft]

    outputs:
      pdf_paths: ${{ steps.set-output.outputs.pdfs }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile LaTeX document ${{ matrix.file }}.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: ${{ matrix.file }}.tex
          args: -synctex=0 -interaction=nonstopmode --shell-escape -pdf -file-line-error

      #- name: Rename output PDF
      #  run: |
      #    mv ${{ matrix.file }}.pdf build-${{ matrix.file }}.pdf

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.file }}-pdf
          path: ${{ matrix.file }}.pdf

  create_release:
    needs: build_latex
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List downloaded files
        run: ls -R artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          files: |
            artifacts/agb_privat-pdf/agb_privat.pdf
            artifacts/agb_geschaeft-pdf/agb_geschaeft.pdf
          body: |
            Automatisch generierter Release mit AGB-Dokumenten.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
